name = "ecom-img-gen-worker"
main = "src/index.ts"
compatibility_date = "2026-05-21"

[[kv_namespaces]]
binding = "TASKS_KV"
id = "6a7ee075ab4b4cbe9cfd80ed9fb0b40a"

[durable_objects]
bindings = [
  { name = "IMAGE_TASKS", class_name = "ImageTasksDO" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ImageTasksDO"]
